config/routes.rb
Rails.application.routes.draw do

  get '/welcome', to: 'welcome#index'

  post '/welcome', to: 'welcome#new' #el boton submit del form me manda por post en /welcome
  # si pongo to: 'welcome#index' podria usar las variables @ en el index y no tendria que 
  #haber hecho la prueba con la vista new de welcome que en realidad no necesito en este proyecto

  get '/tareas', to: 'tareas#index' #si los datos de user son correctos me lleva a esta ruta y controlador
  #para listar las tareas y empezar con el CRUD y otras funcionalidades mas

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tarea.rb
class Tarea < ApplicationRecord
end

app/models/usuario.rb
class Usuario < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tareas_controller.rb
class TareasController < ApplicationController
    def index
      @tareas=Tarea.all
      
    end

    def new

    end

    def create
      
    end
  
    def destroy
      
    end
  end

app/controllers/usuario_controller.rb
class UsuarioController < ApplicationController
  def index
    @probando = "usuariocontroller"
    render "welcome/index"
  end

  def create
    
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @usuarios=Usuario.all
    @tareas=Tarea.all
  end
  def new
    @var_session = params[:session]
    @var_usuario_elegido = @var_session['usuario_elegido']
    @var_password_escrito = @var_session['password_escrito']

    if user = Usuario.find_by(usu_nombre: @var_usuario_elegido, usu_password: @var_password_escrito) #le paso los datos del form y busco en el modelo usuarios
      session[:current_user_id] = user.usu_id
      redirect_to tareas_path
    else
      @usuarios=Usuario.all #para que no me de error cuando hago el render sin declarar la variable que ya tengo en el method index de este controller
      @errorlogin = "Error de inicio intente de nuevo"
      render "index"
    end
  end
  #trabajo los datos de la sesion, cuando
  #hago click en submit del form me toma por defecto la accion new del controller
  #por eso lo uso para hacer otra cosa que no es new nada sino controlar la sesion, no estoy usando .save
  #como se hace usualmente en esta accion "create" predefinida de rails
  def create
    
  end

  def destroy
    # cierro la sesion con el metodo delete
    @_current_user = session[:current_user_id] = nil
    redirect_to root_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/usuario_helper.rb
module UsuarioHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Siloh Fumigaciones</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <meta charset="UTF-8">

    <!-- aca agregue esto para que funcionen los iconos de materialize -->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
 
  </head>

  <body>
    <%= yield %>
    <!-- aca agregue esto para que funcione el select de materialize -->
      <script type="text/javascript">
        document.addEventListener('DOMContentLoaded', function() {
        var elems = document.querySelectorAll('select');
        var instances = M.FormSelect.init(elems, options);
      });
      </script>
  </body>
</html>

app/views/tareas/index.html.erb
<% @tareas.each do |tarea| %>
<h1><%= tarea.tar_descripcion %></h1>
<% end %>

app/views/usuario/index.html.erb
<h1>Usuario#index</h1>
<p>Find me in app/views/usuario/index.html.erb</p>

app/views/welcome/index.html.erb
<div class="container">
            
                      <div class="col l12 s12 m12">
                          <h1>Inicie Sesion Administrador/Empleado</h1>
                          <p><%= @errorlogin %></p>
                      </div>       
                                        <!-- variable :session es un array que contiene los parametros del form session.usuario_elegido por ejemplo -->
                        <%= form_for(:session, url: welcome_path, local: true) do |form| %>
                                	<!--<div class="row">-->
                                                <% options_for_select = Array.new
                                                @usuarios.each do |usuario| %>
                                                <% options_for_select.push(usuario.usu_nombre) %>
                                                <% end %>
                                                <%= form.select :usuario_elegido, options_for_select, :prompt => "Select One", :class => 'select' %>

                                         <i class="material-icons prefix  red-text">lock</i>
                                  	    	<%= form.password_field :password_escrito %>
                                  		
                                	</div>
                        <div class="spinner" id="snipper">
                                <div class="rect1"></div>
                                <div class="rect2"></div>
                                <div class="rect3"></div>        
                                <div class="rect4"></div>
                                <div class="rect5"></div>
                                <div class="rect6"></div>
                                <div class="rect7"></div>
                        </div>
                        <div class="col l5 center-align">
                           <!-- <button class="btn waves-effect waves-light blue" type="submit" name="submit" id="btn_login">Iniciar Sesion</button> -->
                        <%= form.submit "Iniciar Sesion" %>
                        </div>
                     <% end %>

</div><!-- fin del container principal-->

app/views/welcome/new.html.erb
<h1><%= @gg %></h1> <!-- hice esta vista 
para probar que un el metodo de un controller solo pasa la variable @ de ese metodo a la ruta
asociada en routes.rb, si el metodo es "new" entonces se asocia a la carpeta del controller con un 
template new.html.erb, solamente en ese template puedo ver la variable del metodo

esta vista no la uso para nada en realidad, porque welcome solo tiene asociada index para hacer el control
de login de usuarios en la pantalla de bienvenida